### ISSUE TITLE
init app throws opentelemetry errors 

### ISSUE THREAD

**Issue by epsilonhalbe** [liamwh/Veloxide#66]
i tried to get the init app to run

1. there is one step missing from the instructions, to rename .env.example
2. then it runs but i get 'messeage too large in the console for the opentelemetry server

**Comment by liamwh** [comment]
Thanks for reporting this! I'll update the CLI tool to automatically copy the .env.example to be only .env in the near future.

Regarding the Otel issue: I recently updated the repo to use Opentelemetry OLTP instead of the Jaeger exporter. Are you on the version using OLTP or Jaeger? You can find the answer in observability.rs or the veloxide-server Cargo.toml.

**Comment by epsilonhalbe** [comment]
sorry for the late reply, yes i was using the newest version with oltp.

what is your recommendation until they merge the PR?

**Comment by liamwh** [comment]
I also updated the CLI tool to ensure the .env file is copied over as part of [this commit](https://github.com/liamwh/Veloxide-CLI/commit/762e91e34c97cbe57b142e962c6f81d1173991d2). 

Unfortunately, the OpenTelemetry SDK is still not quite 1.0 yet, so we (as the community) are still being subjected to potentially breaking APIs, and consequently stuff like this. I believe the current version is a release candidate however, so hopefully everything becomes stable in the very near future. Until then, our hands are somewhat tied. Really [this PR](https://github.com/tokio-rs/tracing-opentelemetry/pull/12) (which depends on [this one](https://github.com/tokio-rs/tracing-opentelemetry/pull/9)) needs some pressure put on it, so upvoting it, mentioning it in the [Tokio discord](https://discord.com/invite/tokio), and being vocal about it is probably the best bet. It just needs a maintainer from Tokio to review and approve it for things to start moving forward.
